# Generated by Django 3.1.6 on 2021-02-10 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210209_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='acquired_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
